// <auto-generated />
using System;
using CapProj_Updated_.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CapProj_Updated_.Migrations
{
    [DbContext(typeof(TitleContext))]
    [Migration("20210323225148_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CapProj_Updated_.Models.titleBasics", b =>
                {
                    b.Property<string>("endYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("isAdult")
                        .HasColumnType("real");

                    b.Property<string>("originalTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primaryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("runtimeMinutes")
                        .HasColumnType("realzz");

                    b.Property<float?>("startYear")
                        .HasColumnType("real");

                    b.Property<string>("tconst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titleType")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("titleBasics");
                });
#pragma warning restore 612, 618
        }
    }
}
